--create tables
create table CUSTOMERS
( ID NUMBER PRIMARY KEY,
 UPDATE_DATE DATE,
 LOCATION VARCHAR2(100)
);
create table UPD_CUSTOMERS
( SYS_ID NUMBER PRIMARY KEY,
  ID NUMBER,
 UPDATE_DATE DATE,
 LOCATION VARCHAR2(100),
 UPDATE_FLAG VARCHAR2(1) DEFAULT NULL
);

---insert data
INSERT INTO CUSTOMERS values(101,TO_DATE('01.01.2000','%DD.%MM.%YYYY'),'Berlin');
INSERT INTO CUSTOMERS values(102,TO_DATE('02.01.2000','%DD.%MM.%YYYY'),'London');
INSERT INTO CUSTOMERS values(103,TO_DATE('03.01.2000','%DD.%MM.%YYYY'),'Moscow');
INSERT INTO CUSTOMERS values(104,TO_DATE('04.01.2000','%DD.%MM.%YYYY'),'Paris');

INSERT INTO UPD_CUSTOMERS values(1,102,TO_DATE('04.02.2018','%DD.%MM.%YYYY'),'Kiev','U');
INSERT INTO UPD_CUSTOMERS values(2,102,TO_DATE('05.02.2018','%DD.%MM.%YYYY'),'Istanbul','U');
INSERT INTO UPD_CUSTOMERS values(3,103,TO_DATE('05.02.2018','%DD.%MM.%YYYY'),'','D');
INSERT INTO UPD_CUSTOMERS values(4,104,TO_DATE('31.12.1999','%DD.%MM.%YYYY'),'Prague','U');
INSERT INTO UPD_CUSTOMERS values(5,105,TO_DATE('05.02.2018','%DD.%MM.%YYYY'),'Vienna','I');

--commit changes
COMMIT;

--Execute anonymous block on customer_migration.pls
SELECT *
FROM CUSTOMERS;
SELECT *
FROM UPD_CUSTOMERS;

--drop tables
DROP TABLE CUSTOMERS;
DROP TABLE UPD_CUSTOMERS;